services:
  - type: web
    name: hebelwatch
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python LeverageLensServer_1.92_linux.py
    envVars:
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.9.0
